### ISSUE TITLE
Uncaught ReferenceError: FB is not defined 

### ISSUE THREAD

**Issue by theninthnode** [Terumi/AngularJS-Facebook-Login#3]
Hi I just cloned your repo and tried to run it but I'm getting the error:

Uncaught ReferenceError: FB is not defined 

``` javascript
FB.Event.subscribe('auth.statusChange', function(response) {
```

**Comment by Terumi** [comment]
did you include the FB javascript api?

**Comment by theninthnode** [comment]
Does your code in the run() function in app.js not load the FB JS file? Is that what you mean?

**Comment by stevemartingale** [comment]
Hey guys, I had the same issue.  I am using this to make a Canvas App (which may make this a special case) and eventually got something to work.

I manually bootstrap the Angular app after fbAsyncInit and put 

``` javascript
    FB.Event.subscribe('auth.statusChange', function(response) {
        $rootScope.$broadcast("fb_statusChange", {'status': response.status});
    });
```

In appCtrl

And I put 

``` javascript
<script >
    window.fbAsyncInit = function () {
        FB.init({
            appId: '***********************',
            channelUrl : 'channel_url',
            status: true,
            cookie: true,
            xfbml: true,
            oauth: true
        });
        angular.bootstrap(document, ['myApp']);

    };

    (function(d) {
        var js,
            id = 'facebook-jssdk', 
            ref = d.getElementsByTagName('script')[0];
        if (d.getElementById(id)) {
            return;
        }
        js = d.createElement('script');
        js.id = id;
        js.async = true;
        js.src = "//connect.facebook.net/en_US/all.js";
        ref.parentNode.insertBefore(js, ref);
    }(document));
</script>
```

At the bottom of my base template and the problem went away.  I am sure there is a better way around this but so far this is what I've got.

**Comment by theninthnode** [comment]
That fixes that problem thanks. But unfortunately creates a new one. When that second block of code in the script tag is added to my index.html file it stops my page transitions from working. (I'm using ui-router). Will have to try another solution

**Comment by stevemartingale** [comment]
@theninthnode Are you making a canvas app also?

I am also using UI-Router and I had that problem too so I used <a ng-click="$state.transitionTo(desired_state)"> </a> instead of normal links, it works.  Although this seems hacky.

**Comment by theninthnode** [comment]
@stevemartingale I'm just working on a normal html5 SPA. Did you mean to put code in there? "so I used instead of normal links"

**Comment by stevemartingale** [comment]
@theninthnode  oops yes I did mean to put code in there.

``` html
<a ng-click="$state.transitionTo(desired_state)">link</a>
```

**Comment by theninthnode** [comment]
Ah I see thanks. That's not really suitable for me though as I need to use normal href links as I send a post js executed version of the web page to web crawlers.

**Comment by punkbit** [comment]
Hi,

I just cloned your repo and it doesn't work. I also get:

ReferenceError: FB is not defined
[Break On This Error]   

FB.Event.subscribe('auth.statusChange', function(response) {

Can you provide us with a working example, for example in JSBIN or put a note if we need to load something else for this to load ? It's a bit confusing

**Comment by theninthnode** [comment]
Hey guys,

I got this working. I did @stevemartingale 's suggestion but used this code in my index.html instead:

``` javascript
<script >

    window.fbAsyncInit = function() {
        FB.init({
            appId: '****************',
            status: true, 
            cookie: true,
            oauth: true, // enable oauth 2.0
            xfbml: true,
            frictionlessRequests: true,
            channelUrl: 'http://website.dev/channel.html'
        });
    };


    // Load the SDK Asynchronously
    (function(d){
        var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
        js = d.createElement('script'); js.id = id; js.async = true;
        js.src = "//connect.facebook.net/" + 
        "en_US" +
        "/all.js";
        d.getElementsByTagName('head')[0].appendChild(js);
    }(document));
</script>
```

I don't know exactly what makes the difference but this fixed my ui-router transition issues.

**Comment by chug2k** [comment]
I'm not sure I'm doing this correctly just yet, but I bumped that call to `FB.Event.subscribe` above into the body of `window.fbAsyncInit`. https://developers.facebook.com/docs/reference/javascript/ has a little bit of code in there. 

```
// Additional initialization code such as adding Event Listeners goes here
```
