### ISSUE TITLE
Working in phonegap

### ISSUE THREAD

**Issue by gsabater** [Terumi/AngularJS-Facebook-Login#6]
Hi there,
I've managed to make this running in my angularjs APP, but only when i test it on the browser. When i put this on my phonegap project, looks like none of the buttons or functions in the code works.

Any hints in why is this happening?

**Comment by juliabode** [comment]
Could it be that this is a problem with mobile devices? I used this code for my angularjs app, it works perfectly fine in my desktop version, but not all on any mobile device. Is there any solution yet?

**Comment by uniquename** [comment]
The webview opened in phonegap doesn't really handle cookies, so typical php cockie based sessions do not work. Still searching for the best way to handle this...

**Comment by gsabater** [comment]
Abandoned
